= Workshop Exercise - Your Lab Environment

== Objectives

* Understand the lab topology and how to access the environment
* Understand how to perform the workshop exercises
* Understand challenge labs

== Guide

=== Your Lab Environment

The workshop is provisioned with a pre-configured lab environment.
You will have access to a host deployed with Ansible Automation Platform (AAP) which you will use to control the playbook and workflow jobs that automation the RHEL in-place upgrade workflow steps.
You will also have access to some "pet" application hosts, two with RHEL7 and another two with RHEL8.
These are the hosts where we will be upgrading the RHEL operating system (OS).

|===
| Role | Inventory name

| AAP Control Host
| ansible-1

| RHEL7 pet app host 1
| tidy-bengal

| RHEL7 pet app host 2
| strong-hyena

| RHEL8 pet app host 1
| more-calf

| RHEL8 pet app host 2
| upward-moray
|===

____
*Note*

The inventory names of the pet app hosts will be random pet names different from the example above.
// FIXME: The workshop launch page provided by your instructor will list the names actually provisioned with your workshop instance.
We'll dive deeper into why we are using random names in a later exercise.
____

=== Step 1 - Access the Environment

We can use Visual Studio Code (VS Code) as it provides a convenient and intuitive way to use a web browser to edit files and access terminal sessions. Alternatively, you can just connect using SSH in a terminal window.

* If you prefer to just connect using SSH rather than using VS code, paste this command into your terminal:
+
[subs=-macros]
`{ssh_command}`
+
Enter `yes` if you see a "key is not known" warning, then enter the password `{ssh_password}` when promted. 

* To use VS Code, open the link below and enter the password in your web browser:
+
[cols="~,~"]
|===
| Link
| {vscode_server_url}[{vscode_server_url}^]

| Password
| `{vscode_server_password}`
|===
+
____
*Note*

A welcome wizard may appear to guide you through configuring your VS Code user experience.
This is optional as the default settings will work fine for this workshop.
Feel free to step though the wizard to explore the VS code bells and whistles or you may just skip it.
____

=== Step 2 - Open a Terminal Session

Terminal sessions provide access to the RHEL commands and utilities that will help us understand what's going on "behind the curtain" when the RHEL in-place upgrade automation is doing its thing.

* If you are using VS Code, follow this example to open a terminal session:
+
image::new_term.svg[Example of how to open a terminal session in VS Code]

* No matter if you used SSH or VS Code, your terminal session will be running on the AAP control host `ansible-1`.
Use the `cat /etc/hosts` command to see the hostnames of your pet app hosts.
Next, use the `ssh` command to login to one of your pet app hosts.
Finally, use the highlighted commands to confirm the RHEL OS version and kernel version installed.
+
For example:
+
image::ssh_login.svg[Example ssh login to pet app host]

* In the example above, the command `ssh tidy-bengal` connects us to a new session on the named pet app host.
Then the commands `cat /etc/redhat-release` and `uname -r` are used to output the OS release information `Red Hat Enterprise Linux Server release 7.9 (Maipo)` and kernel version `3.10.0-1160.88.1.el7.x86_64` from that host.

=== Step 3 - Access the AAP Web UI

The AAP Web UI is where we will go to submit and check the status of the Ansible playbook jobs we will use to automate the RHEL in-place upgrade workflow.

* Use the link below to open the AAP Web UI in a new web browser tab.
+
[cols="~,~"]
|===
| Link
| {automationcontroller_url}[{automationcontroller_url}^]

| Username
| `{automationcontroller_user_name}`

| Password
| `{automationcontroller_user_password}`
|===

* After entering the username and password on the login page, this will bring you to your AAP Web UI dashboard like the example below:
+
image::aap_console_example.svg[Example AAP Web UI dashboard]

* We will learn more about how to use the AAP Web UI in the next exercise.

=== Step 4 - Access the RHEL Web Console

We will use the RHEL Web Console to review the results of the Leapp pre-upgrade reports we generate for our pet app servers.

* Open a new web browser tab using the link below to access the RHEL Web Console:
+
[cols="~,~"]
|===
| Link
| {cockpit_url}[{cockpit_url}^]

| Username
| `{cockpit_user_name}`

| Password
| `{cockpit_user_password}`
|===

* Enter the username and password provided.
This will bring you to a RHEL Web Console Overview page like the example below:
+
image::cockpit_example.svg[Example RHEL Web Console]

* We will revisit the RHEL Web Console when we are ready to review our pre-upgrade reports in an upcoming exercise.

=== Step 5 - Challenge Labs

You will soon discover that many exercises in the workshop come with a "Challenge Lab" step.
These labs are meant to give you a small task to solve using what you have learned so far.
The solution of the task is shown underneath a warning sign.

== Conclusion

In this exercise, we learned about the lab environment we will be using to continue through the workshop exercises.
We verified that we are able to open terminal sessions to the hosts in the lab environment.
We also made sure we are able to access the AAP Web UI which will be the "self-service portal" we use to perform the next steps of the RHEL in-place upgrade automation workflow.
Finally, we connected to the RHEL Web Console where we will soon be reviewing pre-upgrade reports.

Use the link below to move on the the next exercise.
