= Workshop Exercise - Your Lab Environment

== Objectives

* Understand the lab topology and how to access the environment
* Understand how to perform the workshop exercises
* Understand challenge labs

== Guide

=== Your Lab Environment

The workshop is provisioned with a pre-configured lab environment.
You will have access to a host deployed with Ansible Automation Platform (AAP) which you will use to control the playbook and workflow jobs that automation the RHEL in-place upgrade workflow steps.
You will also have access to some "pet" application hosts, two with RHEL7 and another two with RHEL8.
These are the hosts where we will be upgrading the RHEL operating system (OS).

[cols="1,2"]
|===
| Role | Inventory name

| AAP Control Host
| ansible-1

| RHEL7 pet app host 1
| {node1_petname}

| RHEL7 pet app host 2
| {node2_petname}

| RHEL8 pet app host 1
| {node3_petname}

| RHEL8 pet app host 2
| {node4_petname}
|===

We'll dive deeper into why we are using random names in a later exercise.

=== Step 1 - Access the Environment

If you are viewing this exercise using the Showroom experience, you will see a terminal session frame on the right side of this browser tab.

* Verify you see the ASCII art Red Hat logo and `[student@ansible-1 ~]$` shell prompt in the terminal session frame.
+
* If you prefer to directly connect using SSH rather than using browser-based terminal, you can open your own terminal app and paste this command:
+
[%nowrap,source,bash,role=execute,subs=attributes+]
----
{ssh_command}
----
+
Enter `yes` if you see a "key is not known" warning, then enter the password `{ssh_password}` when promted.
+
* In either case, you should now see a logged in session that looks like this:
+
image::terminal_login.svg[Example ssh login to ansible-1 shell prompt]

=== Step 2 - Using the Terminal Session

Terminal sessions provide access to the RHEL commands and utilities that will help us understand what's going on "behind the curtain" when the RHEL in-place upgrade automation is doing its thing.

* Your terminal session will be running on the AAP control host.
Use the `cat /etc/hosts` command to verify the hostnames of your pet app hosts.
Next, use the `ssh` command to login to one of your pet app hosts, for example:
+
[%nowrap,source,bash,role=execute,subs=attributes+]
----
ssh {node1_petname}
----
+
Finally, use these commands to confirm the RHEL OS version and kernel version installed:
+
[%nowrap,source,bash,role=execute,subs=attributes+]
----
cat /etc/redhat-release
uname -r
----
+
For example:
+
image::rhel_and_kernel_versions.svg[Command output showing the RHEL and kernel versions]
+
* In the example above, the ssh command connected us to a new session on the named pet app host.
+
* Then the commands `cat /etc/redhat-release` and `uname -r` are used to output the OS release information `Red Hat Enterprise Linux Server release 7.9 (Maipo)` and kernel version `3.10.0-1160.114.2.el7.x86_64` from that host.

=== Step 3 - Access the AAP Web UI

The AAP Web UI is where we will go to submit and check the status of the Ansible playbook jobs we will use to automate the RHEL in-place upgrade workflow.

* Use the link below to open the AAP Web UI in a new web browser tab.
+
[cols="~,~"]
|===
| Link
| {automationcontroller_url}[{automationcontroller_url}^]

| Username
| `{automationcontroller_user_name}`

| Password
| `{automationcontroller_user_password}`
|===

* After entering the username and password on the login page, this will bring you to your AAP Web UI dashboard like the example below:
+
image::aap_console_example.svg[Example AAP Web UI dashboard]

* We will learn more about how to use the AAP Web UI in the next exercise.

=== Step 4 - Access the RHEL Web Console

We will use the RHEL Web Console to review the results of the Leapp pre-upgrade reports we generate for our pet app servers.

* Open a new web browser tab using the link below to access the RHEL Web Console:
+
[cols="~,~"]
|===
| Link
| {cockpit_url}[{cockpit_url}^]

| Username
| `{cockpit_user_name}`

| Password
| `{cockpit_user_password}`
|===

* Enter the username and password provided.
This will bring you to a RHEL Web Console Overview page like the example below:
+
image::cockpit_example.svg[Example RHEL Web Console]

* We will revisit the RHEL Web Console when we are ready to review our pre-upgrade reports in an upcoming exercise.

=== Step 5 - Challenge Labs

You will soon discover that many exercises in the workshop come with a "Challenge Lab" step.
These labs are meant to give you a small task to solve using what you have learned so far.
The solution of the task is shown underneath a warning sign.

== Conclusion

In this exercise, we learned about the lab environment we will be using to continue through the workshop exercises.
We verified that we are able to open terminal sessions to the hosts in the lab environment.
We also made sure we are able to access the AAP Web UI which will be the "self-service portal" we use to perform the next steps of the RHEL in-place upgrade automation workflow.
Finally, we connected to the RHEL Web Console where we will soon be reviewing pre-upgrade reports.

Use the link below to move on the the next exercise.
